spring:
  application:
    name: myclub

  datasource:
    url: jdbc:mysql://localhost:3306/myclub?useSSL=false&serverTimezone=UTC
    username: root
    password: Amira_2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # crée/maj les tables automatiquement depuis les entités Java
    show-sql: true            # affiche les requêtes SQL dans la console
    properties:
      hibernate:
        format_sql: true       # formate joliment le SQL affiché
    database-platform: org.hibernate.dialect.MySQL8Dialect  # dialecte MySQL

server:
  port: 8080
